### ISSUE TITLE
PCF8574t  it will work??

### ISSUE THREAD

**Issue by 9acca9** [dbrgn/RPLCD#107]
Hi, i found in you library that
"Supported port expanders are the PCF8574, the MCP23008 and the MCP23017."

Sorry my ignorance, but it will work with a "PCF8574t"??? I have to change something? if yes, what??

(i dont speak english)
Thanks!

**Comment by dbrgn** [comment]
I'm not sure, you'd have to check out the datasheets to compare the functionality, or simply try it out.

I would guess that it should work, but I don't know what the difference between versions with the `t` and versions without are.

Let me know if you need anything else.

**Comment by SlySven** [comment]
Of course the OP could be referring to the PCF8574**A** which is functionally identical to the one without the suffix but *which has a different range of possible I2C addresses* - but in this case it is because he has an SMD (Surface Mount Device) rather than a DIL (Dual In-Line - i.e. with pins that go into holes on a printed circuit board) one - as we can see from the [documentation](https://www.nxp.com/docs/en/data-sheet/PCF8574_PCF8574A.pdf):

![image](https://user-images.githubusercontent.com/6163092/71694996-c15bdc80-2da8-11ea-812a-f3961882be88.png)

for the addresses used the details are:
![image](https://user-images.githubusercontent.com/6163092/71695278-860ddd80-2da9-11ea-962b-af19597d8270.png)
![image](https://user-images.githubusercontent.com/6163092/71695347-b9506c80-2da9-11ea-81b0-9203b73b882b.png)
